name: 'Build and Release'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '18.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.2'
      - run: flutter pub get
      - run: flutter build apk --debug --split-per-abi
      - name: push to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"  # , build/ios/iphoneos/app.ipa"
          tag: v1.0.${{github.run_number}}
          token: ${{secrets.TOKEN}}
